# Site settings
title: "Akash Agarwal"
email: akash.f2290@gmail.com
description: "A website about me..."
baseurl: ""
url: "https://akashagarwalgit.github.io/"
title_description: ""
title_image: "https://secure.gravatar.com/avatar/14bfd71f98b32d91a447ccce85aa0e18?s=250"
google_analytics: ""
disqus_account:
github_repository: https://github.com/AkashAgarwalGit/AkashAgarwalGit.github.io
addthis_id:
post_limit:

# Social usernames/URLs
twitter_username: asliakash
github_username:  AkashAgarwalGit
instagram_username:
reddit_username:
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/asliakash\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/AkashAgarwalGit\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
